apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    {{- include "stuufff.labels" . | nindent 4 }}
    app.kubernetes.io/name: stuufff
    app.kubernetes.io/component: postgres
spec:
  storageClassName: zfs-local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
