apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  labels:
    {{- include "stuufff.labels" . | nindent 4 }}
    app.kubernetes.io/name: stuufff
    app.kubernetes.io/component: stuufff
spec:
  storageClassName: zfs-local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
