apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    {{- include "stuufff.labels" . | nindent 4 }}
    app.kubernetes.io/name: stuufff
    app.kubernetes.io/component: stuufff
  name: stuufff
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stuufff
      app.kubernetes.io/component: stuufff
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: stuufff
        app.kubernetes.io/component: stuufff
    spec:
      volumes:
      - name: postgres-admin
        secret:
          secretName: postgres-admin
          defaultMode: 0440
      - name: integrations
        secret:
          secretName: integrations
          defaultMode: 0440
      - name: media
        persistentVolumeClaim:
          claimName: media
      - name: tmp
        emptyDir: {}
      - name: run
        emptyDir: {}
      {{- toYaml .Values.podSecurityOpts.stuufff | nindent 6 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext.stuufff | nindent 8 }}
      initContainers:
      - name: init-stuufff
        image: {{ .Values.images.stuufff }}
        imagePullPolicy: Always
        command: ["stuufff", "db", "migrate"]
        env:
        - name: PSQL_HOST
          value: postgres
        volumeMounts:
        - name: postgres-admin
          mountPath: /etc/secrets/psql
          readOnly: true
      containers:
      - name: stuufff
        image: {{ .Values.images.stuufff }}
        imagePullPolicy: Always
        args: ["api"]
        volumeMounts:
        - name: postgres-admin
          mountPath: /etc/secrets/psql
          readOnly: true
        - name: integrations
          mountPath: /etc/secrets/integrations
          readOnly: true
        - name: media
          mountPath: /var/lib/stuufff/media
        env:
        - name: PSQL_HOST
          value: postgres
        - name: MEDIA_FOLDER
          value: /var/lib/stuufff/media
        securityContext:
          {{- toYaml .Values.containerSecurityContext.stuufff | nindent 10 }}
        resources:
          {{- include "stuufff.resources" .Values.resources.stuufff | nindent 10 }}
