// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::psql::schema::*;

use chrono::DateTime;
use chrono::offset::Utc;
use diesel::prelude::*;
#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
    Identifiable,
)]
#[diesel(primary_key(audit_id))]
#[diesel(table_name = audit_labels)]
pub struct AuditLabel {
    pub audit_id: i64,
    pub operation: String,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<String>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
    Identifiable,
)]
#[diesel(primary_key(audit_id))]
#[diesel(table_name = audit_places)]
pub struct AuditPlace {
    pub audit_id: i64,
    pub operation: String,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<String>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
    Identifiable,
)]
#[diesel(primary_key(audit_id))]
#[diesel(table_name = audit_reserved_things)]
pub struct AuditReservedThing {
    pub audit_id: i64,
    pub operation: String,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<String>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
    Identifiable,
)]
#[diesel(primary_key(audit_id))]
#[diesel(table_name = audit_thing_labels)]
pub struct AuditThingLabel {
    pub audit_id: i64,
    pub operation: String,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<String>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
    Identifiable,
)]
#[diesel(primary_key(audit_id))]
#[diesel(table_name = audit_things)]
pub struct AuditThing {
    pub audit_id: i64,
    pub operation: String,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<String>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
)]
#[diesel(table_name = labels)]
pub struct Label {
    pub id: i32,
    pub name: String,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
)]
#[diesel(table_name = places)]
pub struct Place {
    pub id: i32,
    pub in_place: Option<i32>,
    pub name: String,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
)]
#[diesel(table_name = reserved_things)]
pub struct ReservedThing {
    pub id: i32,
    pub thing_id: i32,
    pub count: i32,
    pub reserved_by: String,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
)]
#[diesel(table_name = thing_labels)]
pub struct ThingLabel {
    pub id: i32,
    pub thing_id: i32,
    pub label_id: i32,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
)]
#[diesel(table_name = things)]
pub struct Thing {
    pub id: i32,
    pub count: i32,
    pub in_place: Option<i32>,
    pub name: String,
    pub description: String,
}
