// Generated by diesel_ext (insertable structs)

#![allow(unused)]
#![allow(clippy::all)]

use crate::psql::schema::*;
use chrono::DateTime;
use chrono::offset::Utc;
use diesel::prelude::Insertable;
use uuid::Uuid;
#[derive(Insertable)]
#[diesel(table_name = audit_department_images)]
pub struct NewAuditDepartmentImage<'a> {
    pub audit_id: i64,
    pub operation: &'a str,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<&'a str>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(Insertable)]
#[diesel(table_name = audit_departments)]
pub struct NewAuditDepartment<'a> {
    pub audit_id: i64,
    pub operation: &'a str,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<&'a str>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(Insertable)]
#[diesel(table_name = audit_labels)]
pub struct NewAuditLabel<'a> {
    pub audit_id: i64,
    pub operation: &'a str,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<&'a str>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(Insertable)]
#[diesel(table_name = audit_place_images)]
pub struct NewAuditPlaceImage<'a> {
    pub audit_id: i64,
    pub operation: &'a str,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<&'a str>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(Insertable)]
#[diesel(table_name = audit_places)]
pub struct NewAuditPlace<'a> {
    pub audit_id: i64,
    pub operation: &'a str,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<&'a str>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(Insertable)]
#[diesel(table_name = audit_reserved_places)]
pub struct NewAuditReservedPlace<'a> {
    pub audit_id: i64,
    pub operation: &'a str,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<&'a str>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(Insertable)]
#[diesel(table_name = audit_reserved_things)]
pub struct NewAuditReservedThing<'a> {
    pub audit_id: i64,
    pub operation: &'a str,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<&'a str>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(Insertable)]
#[diesel(table_name = audit_thing_images)]
pub struct NewAuditThingImage<'a> {
    pub audit_id: i64,
    pub operation: &'a str,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<&'a str>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(Insertable)]
#[diesel(table_name = audit_thing_labels)]
pub struct NewAuditThingLabel<'a> {
    pub audit_id: i64,
    pub operation: &'a str,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<&'a str>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(Insertable)]
#[diesel(table_name = audit_things)]
pub struct NewAuditThing<'a> {
    pub audit_id: i64,
    pub operation: &'a str,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<&'a str>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(Insertable)]
#[diesel(table_name = department_images)]
pub struct NewDepartmentImage {
    pub department_id: i32,
}

#[derive(Insertable)]
#[diesel(table_name = departments)]
pub struct NewDepartment<'a> {
    pub name: &'a str,
    pub main_img: Option<Uuid>,
}

#[derive(Insertable)]
#[diesel(table_name = labels)]
pub struct NewLabel<'a> {
    pub color: Option<&'a str>,
    pub name: &'a str,
    pub description: Option<&'a str>,
}

#[derive(Insertable)]
#[diesel(table_name = place_images)]
pub struct NewPlaceImage {
    pub place_id: i32,
}

#[derive(Insertable)]
#[diesel(table_name = places)]
pub struct NewPlace<'a> {
    pub in_place: Option<i32>,
    pub in_department: Option<i32>,
    pub name: &'a str,
    pub description: Option<&'a str>,
    pub main_img: Option<Uuid>,
}

#[derive(Insertable)]
#[diesel(table_name = reserved_places)]
pub struct NewReservedPlace<'a> {
    pub place_id: i32,
    pub reserved_by: &'a str,
}

#[derive(Insertable)]
#[diesel(table_name = reserved_things)]
pub struct NewReservedThing<'a> {
    pub thing_id: i32,
    pub count: i32,
    pub reserved_by: &'a str,
}

#[derive(Insertable)]
#[diesel(table_name = thing_images)]
pub struct NewThingImage {
    pub thing_id: i32,
}

#[derive(Insertable)]
#[diesel(table_name = thing_labels)]
pub struct NewThingLabel {
    pub thing_id: i32,
    pub label_id: i32,
}

#[derive(Insertable)]
#[diesel(table_name = things)]
pub struct NewThing<'a> {
    pub count: i32,
    pub in_place: Option<i32>,
    pub name: &'a str,
    pub description: Option<&'a str>,
    pub main_img: Option<Uuid>,
}
