// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::psql::schema::*;

use chrono::DateTime;
use chrono::offset::Utc;
use diesel::prelude::*;
#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
    Identifiable,
)]
#[diesel(primary_key(audit_id))]
#[diesel(table_name = audit_boxes)]
pub struct AuditBoxe {
    pub audit_id: i64,
    pub operation: String,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<String>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
    Identifiable,
)]
#[diesel(primary_key(audit_id))]
#[diesel(table_name = audit_item_labels)]
pub struct AuditItemLabel {
    pub audit_id: i64,
    pub operation: String,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<String>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
    Identifiable,
)]
#[diesel(primary_key(audit_id))]
#[diesel(table_name = audit_item_reservations)]
pub struct AuditItemReservation {
    pub audit_id: i64,
    pub operation: String,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<String>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
    Identifiable,
)]
#[diesel(primary_key(audit_id))]
#[diesel(table_name = audit_items)]
pub struct AuditItem {
    pub audit_id: i64,
    pub operation: String,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<String>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
    Identifiable,
)]
#[diesel(primary_key(audit_id))]
#[diesel(table_name = audit_labels)]
pub struct AuditLabel {
    pub audit_id: i64,
    pub operation: String,
    pub changed_at: Option<DateTime<Utc>>,
    pub changed_by: Option<String>,
    pub old_data: Option<serde_json::Value>,
    pub new_data: Option<serde_json::Value>,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
)]
#[diesel(table_name = boxes)]
pub struct Boxe {
    pub id: i32,
    pub name: String,
    pub reserved_by: Option<String>,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
)]
#[diesel(table_name = item_labels)]
pub struct ItemLabel {
    pub id: i32,
    pub item_id: i32,
    pub label_id: i32,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
)]
#[diesel(table_name = item_reservations)]
pub struct ItemReservation {
    pub id: i32,
    pub item_id: i32,
    pub count: i32,
    pub reserved_by: String,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
)]
#[diesel(table_name = items)]
pub struct Item {
    pub id: i32,
    pub box_id: Option<i32>,
    pub count: i32,
    pub title: String,
    pub description: String,
}

#[derive(
    Queryable,
    Selectable,
    Insertable,
    AsChangeset,
    Debug,
    Clone,
    serde::Serialize,
    core::cmp::Eq,
    core::cmp::PartialEq,
    core::hash::Hash,
)]
#[diesel(table_name = labels)]
pub struct Label {
    pub id: i32,
    pub name: Option<String>,
}
